Document: svg-stacker
Title: Debian svg-stacker Manual
Author: <insert document author here>
Abstract: This manual describes what svg-stacker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/svg-stacker/svg-stacker.sgml.gz

Format: postscript
Files: /usr/share/doc/svg-stacker/svg-stacker.ps.gz

Format: text
Files: /usr/share/doc/svg-stacker/svg-stacker.text.gz

Format: HTML
Index: /usr/share/doc/svg-stacker/html/index.html
Files: /usr/share/doc/svg-stacker/html/*.html
